### ISSUE TITLE
Support for using existing clusters in DatabricksNotebookOperator

### ISSUE THREAD

**Issue by Hang1225** [astronomer/astro-provider-databricks#70]
## Issue
The parameter "existing_cluster_id" for DatabricksNotebookOperator is not being utilized. 

Our teams at HealthPartners have several use cases of using a job compute and shared compute within a workflow for different tasks. However the ability to use different computes (other than job) is not supported as only the job_cluster parameter is evaluated when constructing the JSON for a new workflow. 

## Proposed Solution
Under "convert_to_databricks_workflow_task" function in operators/notebook.py: 
* add key='existing_cluster_id' and value=self.existing_cluster_id to the variable `result` if self.existing_cluster_id is not empty.
* add key='job_cluster_key' and value=self.job_cluster_key to the variable 'result' if self.existing_cluster_id is empty.
* PR: https://github.com/astronomer/astro-provider-databricks/pull/73

**Comment by pankajkoti** [comment]
Hi 👋🏽 ,

Thanks a lot for trying to support the repository with your contribution.

I believe you would not be blocked from contributing.
You could take the following steps for your contribution
1. Create your own from for the repo. You would see a fork icon in the top right section of the repo.
2. Create a branch in your forked repo and push commits to it
3. Come back to the original repo and click on pull requests
4. Try to create a pull request against your forked repo + branch

Next the reviewers will review your pull request and merge the PR and your code will be merged to the original repo

The below links will guide you step by step on how exactly to do the above steps I mentioned.
1. https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/fork-a-repo
2. https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork

Please let me know if I can offer additional help. Happy to collaborate further!
